In [1]:
import tensorflow as tf
import keras
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [7]:
X_train,X_test = x_train/255.0,x_test/255.0

In [8]:
X_train.shape

(60000, 28, 28)

In [11]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [12]:
x_train.shape

(60000, 28, 28)

In [7]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [17]:
x_train[:1].shape

(1, 28, 28)

In [18]:
x_train[:1].flatten().shape #784 neurons in first dense layer,

(784,)

In [14]:
x_train[:1].ndim

3

In [16]:
x_train[:1].flatten().ndim

1

In [19]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.49769312,  0.22329634,  0.07974998,  0.29837275, -0.0015975 ,
         0.22943896, -0.33195576, -1.0779502 , -0.7950165 , -0.25839522]],
      dtype=float32)

In [15]:
tf.nn.softmax(predictions).numpy()

array([[0.08179104, 0.06488211, 0.15905182, 0.06726331, 0.05519492,
        0.13446648, 0.12259384, 0.09216341, 0.09769117, 0.12490193]],
      dtype=float32)

In [22]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [23]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [21]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 128)               100480    
                                                                 
 dropout (Dropout)           (None, 128)               0         
                                                                 
 dense_1 (Dense)             (None, 10)                1290      
                                                                 
Total params: 101770 (397.54 KB)
Trainable params: 101770 (397.54 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [18]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


1875/1875 [==============================] - 5s 2ms/step - loss: 0.2959 - accuracy: 0.9147
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1440 - accuracy: 0.9572
Epoch 3/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.1088 - accuracy: 0.9666
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0877 - accuracy: 0.9730
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0753 - accuracy: 0.9762


In [19]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0712 - accuracy: 0.9772 - 562ms/epoch - 2ms/step


[0.0711684599518776, 0.9771999716758728]

In [30]:
model.get_weights()

[array([[ 0.03674138, -0.04791379,  0.06277794, ...,  0.06720217,
         -0.01266268,  0.0169372 ],
        [ 0.02375954, -0.08014606,  0.07305358, ...,  0.01390188,
          0.0686195 , -0.00575618],
        [ 0.0023245 , -0.07982307, -0.00663101, ..., -0.03740327,
         -0.06192255,  0.04719866],
        ...,
        [ 0.06343453, -0.02320062, -0.00951858, ..., -0.01351115,
          0.0453661 , -0.00028021],
        [ 0.0689164 , -0.00771707, -0.04608609, ...,  0.05029691,
          0.0784382 ,  0.01431684],
        [ 0.07702861,  0.02083938, -0.06898914, ...,  0.02035505,
         -0.04287396, -0.04915806]], dtype=float32),
 array([ 0.00099967, -0.00099471,  0.0009998 , -0.0009996 ,  0.00099873,
        -0.0009945 ,  0.00099983, -0.0009995 , -0.00099995, -0.00099991,
         0.00099954,  0.00099961,  0.00099985,  0.00099971, -0.00099959,
         0.00099978,  0.00099922,  0.00099964,  0.00099978,  0.        ,
         0.00099975, -0.00099974,  0.00099935,  0.00099904, -0.000

In [ ]:
model.add(layers.

In [ ]:
model.add(layers.Conv2D(32,(3,3),activation= 'relu',input_shape = (32,32,3))